version: '3.5'

services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data/caddy:/etc/caddy
      - ./data/config:/config
      - ./data/data:/data
